volumes:
  mysql_data:
  redis-data:
services:
  finance-assistant-db-service:
    image: mysql
    build: ./finance-assistant-db-service
    container_name: finance-assistant-db-service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  finance-assistant-api-service:
    image: node
    build: ./finance-assistant-api-service
    container_name: finance-assistant-api-service
    depends_on:
      - finance-assistant-db-service

    ports:
      - "3000:3000"
      - "9229:9229"

    command: sh -c "npx sequelize-cli db:migrate && chmod +x ./wait.sh && ./wait.sh finance-assistant-db-service:3306 && npm run dev"

    volumes:
      - ./finance-assistant-api-service/src:/finance-assistant-api-service/src # Mount your code
      - /finance-assistant-api-service/node_modules # Prevent host from overwriting container node_modules
    environment:
      DB_HOST: finance-assistant-db-service
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: sampledb

  finance-assistant-redis-service:
    image: redis:latest
    container_name: finance-assistant-redis-service
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--requirepass",
        "yourStrongPassword",
      ]
  finance-assistant-client:
    build: ./finance-assistant-client
    container_name: finance-assistant-client
    ports:
      - "8080:80"
